version: '3.8'
services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: backend_app
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "8080:80"
